### ISSUE TITLE
Compatibility of examples with Python 3

### ISSUE THREAD

**Issue by niknow** [slawek87/geolocation-python#21]
Hi,

I've noticed that the `README.md` states that the project is compatible with Python 2 and Python 3. However, the scripts in the `examples` are not compatible with Python 3. As far as I can see, this is mainly due to the `print` statements and should be easy to fix.

Unless of course there is a reason you sticked to the Python 2 syntax? In case not, would you be happy if I fix that and make another pull request?

**Comment by slawek87** [comment]
Hi Niknow! :)

Sure! I have only experience in python 2.7... and I've never use python 3.. please fix it.. I'll merge it to master branch :)

p.s.

We have still some issue with tests.. we have to use there mockups.. because google api update data each day.. maybe we can resolve that issue together.

**Comment by niknow** [comment]
Alright, I'll take a look at the Python 3 compatibility of the example scripts then. 

P.S.: You are right. It would be cool, if one could resolve the issues with the tests and I also agree that mock objects are probably helpful here. I have to take a closer look though. I'm having the feeling that this is probably a more complex issue, so let's open a new issue for that. ;)
